{"text": "2022-07-16T20:45:10.280188+0300 | ERROR      | An error has been caught in function 'get_users', process 'MainProcess' (11436), thread 'MainThread' (17788):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 134, in get_users\n    view = ListEmbedsView(\n           └ <class 'slavebot.views.ListEmbedsView'>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\views.py\", line 405, in __init__\n    self.menu = MasterMembers(\n    │           └ <class 'slavebot.views.MasterMembers'>\n    └ <ListEmbedsView timeout=300 children=1>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\views.py\", line 354, in __init__\n    raise ValueError(\"Слишком много пользователей\")\n\nValueError: Слишком много пользователей\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\bot.py\", line 77, in <module>\n    bot.run(config.get_token)\n    │   │   │      └ <property object at 0x0000026A704AEF70>\n    │   │   └ <_config.Config object at 0x0000026A6E6E7A30>\n    │   └ <function Client.run at 0x0000026A6F1FD5A0>\n    └ <nextcord.ext.commands.bot.Bot object at 0x0000026A70726290>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 796, in run\n    loop.run_forever()\n    │    └ <function ProactorEventLoop.run_forever at 0x0000026A6E4F0D30>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 600, in run_forever\n    self._run_once()\n    │    └ <function BaseEventLoop._run_once at 0x0000026A6E43E0E0>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1896, in _run_once\n    handle._run()\n    │      └ <function Handle._run at 0x0000026A6E3D1900>\n    └ <Handle Task.task_wakeup(<Future finished result=None>)>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n    │    │            │    │           │    └ <member '_args' of 'Handle' objects>\n    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>\n    │    │            │    └ <member '_callback' of 'Handle' objects>\n    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>\n    │    └ <member '_context' of 'Handle' objects>\n    └ <Handle Task.task_wakeup(<Future finished result=None>)>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 445, in _run_event\n    await coro(*args, **kwargs)\n          │     │       └ {}\n          │     └ (<nextcord.interactions.Interaction object at 0x0000026A70712190>,)\n          └ <bound method Client.on_interaction of <nextcord.ext.commands.bot.Bot object at 0x0000026A70726290>>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 1872, in on_interaction\n    await self.process_application_commands(interaction)\n          │    │                            └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n          │    └ <function Client.process_application_commands at 0x0000026A6F1FEE60>\n          └ <nextcord.ext.commands.bot.Bot object at 0x0000026A70726290>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 1892, in process_application_commands\n    await app_cmd.call_from_interaction(interaction)\n          │       │                     └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n          │       └ <function BaseApplicationCommand.call_from_interaction at 0x0000026A6F16B2E0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000026A707A29B0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 2045, in call_from_interaction\n    await self.call(self._state, interaction)  # type: ignore\n          │    │    │    │       └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n          │    │    │    └ <nextcord.state.ConnectionState object at 0x0000026A707274C0>\n          │    │    └ <nextcord.application_command.SlashApplicationCommand object at 0x0000026A707A29B0>\n          │    └ <function SlashApplicationCommand.call at 0x0000026A6F16BBE0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000026A707A29B0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 2397, in call\n    await self.call_slash(state, interaction, option_data)\n          │    │          │      │            └ [{'value': '794994804018642965', 'type': 8, 'name': 'guild_role'}]\n          │    │          │      └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n          │    │          └ <nextcord.state.ConnectionState object at 0x0000026A707274C0>\n          │    └ <function SlashCommandMixin.call_slash at 0x0000026A6F16A830>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000026A707A29B0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 1514, in call_slash\n    await self.invoke_callback_with_hooks(state, interaction, **kwargs)\n          │    │                          │      │              └ {'guild_role': <Role id=794994804018642965 name='⠀'>}\n          │    │                          │      └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n          │    │                          └ <nextcord.state.ConnectionState object at 0x0000026A707274C0>\n          │    └ <function CallbackMixin.invoke_callback_with_hooks at 0x0000026A6F169900>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000026A707A29B0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 824, in invoke_callback_with_hooks\n    await self(interaction, *args, **kwargs)\n          │    │             │       └ {'guild_role': <Role id=794994804018642965 name='⠀'>}\n          │    │             └ ()\n          │    └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000026A707A29B0>\n\n> File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 141, in get_users\n    return await self.bad_callback(\n                 │    └ <function DataMixin.bad_callback at 0x0000026A706E9990>\n                 └ <cogs.master.MasterCommands object at 0x0000026A707A2950>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\utils.py\", line 163, in bad_callback\n    return await interaction.send(\n                 │           └ <function Interaction.send at 0x0000026A6F1176D0>\n                 └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\interactions.py\", line 523, in send\n    return await self.response.send_message(\n                 │    └ <nextcord.utils.CachedSlotProperty object at 0x0000026A6F070610>\n                 └ <nextcord.interactions.Interaction object at 0x0000026A70712190>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\interactions.py\", line 852, in send_message\n    await adapter.create_interaction_response(\n          │       └ <function AsyncWebhookAdapter.create_interaction_response at 0x0000026A6F10FC70>\n          └ <nextcord.webhook.async_.AsyncWebhookAdapter object at 0x0000026A6F0B6680>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\webhook\\async_.py\", line 204, in request\n    raise NotFound(response, data)\n          │        │         └ {'message': 'Unknown interaction', 'code': 10062}\n          │        └ <ClientResponse(https://discord.com/api/v10/interactions/997921651150827703/aW50ZXJhY3Rpb246OTk3OTIxNjUxMTUwODI3NzAzOkpxcW96d...\n          └ <class 'nextcord.errors.NotFound'>\n\nnextcord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n", "record": {"elapsed": {"repr": "0:00:51.942004", "seconds": 51.942004}, "exception": {"type": "NotFound", "value": "404 Not Found (error code: 10062): Unknown interaction", "traceback": true}, "extra": {}, "file": {"name": "master.py", "path": "C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py"}, "function": "get_users", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 141, "message": "An error has been caught in function 'get_users', process 'MainProcess' (11436), thread 'MainThread' (17788):", "module": "master", "name": "cogs.master", "process": {"id": 11436, "name": "MainProcess"}, "thread": {"id": 17788, "name": "MainThread"}, "time": {"repr": "2022-07-16 20:45:10.280188+03:00", "timestamp": 1657993510.280188}}}
{"text": "2022-07-16T20:54:15.702183+0300 | ERROR      | An error has been caught in function 'get_users', process 'MainProcess' (18124), thread 'MainThread' (14408):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 134, in get_users\n    view = ListEmbedsView(\n           └ <class 'slavebot.views.ListEmbedsView'>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\views.py\", line 405, in __init__\n    self.menu = MasterMembers(\n    │           └ <class 'slavebot.views.MasterMembers'>\n    └ <ListEmbedsView timeout=300 children=1>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\views.py\", line 354, in __init__\n    raise ValueError(\"Слишком много пользователей\")\n\nValueError: Слишком много пользователей\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\bot.py\", line 77, in <module>\n    bot.run(config.get_token)\n    │   │   │      └ <property object at 0x0000022B2E16EF70>\n    │   │   └ <_config.Config object at 0x0000022B2C3A7A30>\n    │   └ <function Client.run at 0x0000022B2CEBD5A0>\n    └ <nextcord.ext.commands.bot.Bot object at 0x0000022B2A525840>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 796, in run\n    loop.run_forever()\n    │    └ <function ProactorEventLoop.run_forever at 0x0000022B2C1E0D30>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 600, in run_forever\n    self._run_once()\n    │    └ <function BaseEventLoop._run_once at 0x0000022B2C12E0E0>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1896, in _run_once\n    handle._run()\n    │      └ <function Handle._run at 0x0000022B2C0D1900>\n    └ <Handle Task.task_wakeup(<Future finished result=None>)>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n    │    │            │    │           │    └ <member '_args' of 'Handle' objects>\n    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>\n    │    │            │    └ <member '_callback' of 'Handle' objects>\n    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>\n    │    └ <member '_context' of 'Handle' objects>\n    └ <Handle Task.task_wakeup(<Future finished result=None>)>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 445, in _run_event\n    await coro(*args, **kwargs)\n          │     │       └ {}\n          │     └ (<nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>,)\n          └ <bound method Client.on_interaction of <nextcord.ext.commands.bot.Bot object at 0x0000022B2A525840>>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 1872, in on_interaction\n    await self.process_application_commands(interaction)\n          │    │                            └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n          │    └ <function Client.process_application_commands at 0x0000022B2CEBEE60>\n          └ <nextcord.ext.commands.bot.Bot object at 0x0000022B2A525840>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 1892, in process_application_commands\n    await app_cmd.call_from_interaction(interaction)\n          │       │                     └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n          │       └ <function BaseApplicationCommand.call_from_interaction at 0x0000022B2CE2B2E0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000022B2E4628F0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 2045, in call_from_interaction\n    await self.call(self._state, interaction)  # type: ignore\n          │    │    │    │       └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n          │    │    │    └ <nextcord.state.ConnectionState object at 0x0000022B2E3E6B90>\n          │    │    └ <nextcord.application_command.SlashApplicationCommand object at 0x0000022B2E4628F0>\n          │    └ <function SlashApplicationCommand.call at 0x0000022B2CE2BBE0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000022B2E4628F0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 2397, in call\n    await self.call_slash(state, interaction, option_data)\n          │    │          │      │            └ [{'value': '794994804018642965', 'type': 8, 'name': 'guild_role'}]\n          │    │          │      └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n          │    │          └ <nextcord.state.ConnectionState object at 0x0000022B2E3E6B90>\n          │    └ <function SlashCommandMixin.call_slash at 0x0000022B2CE2A830>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000022B2E4628F0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 1514, in call_slash\n    await self.invoke_callback_with_hooks(state, interaction, **kwargs)\n          │    │                          │      │              └ {'guild_role': <Role id=794994804018642965 name='⠀'>}\n          │    │                          │      └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n          │    │                          └ <nextcord.state.ConnectionState object at 0x0000022B2E3E6B90>\n          │    └ <function CallbackMixin.invoke_callback_with_hooks at 0x0000022B2CE29900>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000022B2E4628F0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 824, in invoke_callback_with_hooks\n    await self(interaction, *args, **kwargs)\n          │    │             │       └ {'guild_role': <Role id=794994804018642965 name='⠀'>}\n          │    │             └ ()\n          │    └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x0000022B2E4628F0>\n\n> File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 141, in get_users\n    return await self.bad_callback(\n                 │    └ <function DataMixin.bad_callback at 0x0000022B2E3B9AB0>\n                 └ <cogs.master.MasterCommands object at 0x0000022B2E462890>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\utils.py\", line 163, in bad_callback\n    return await interaction.send(\n                 │           └ <function Interaction.send at 0x0000022B2CDD76D0>\n                 └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\interactions.py\", line 523, in send\n    return await self.response.send_message(\n                 │    └ <nextcord.utils.CachedSlotProperty object at 0x0000022B2CD305E0>\n                 └ <nextcord.interactions.Interaction object at 0x0000022B2E3FAB50>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\interactions.py\", line 852, in send_message\n    await adapter.create_interaction_response(\n          │       └ <function AsyncWebhookAdapter.create_interaction_response at 0x0000022B2CDCFC70>\n          └ <nextcord.webhook.async_.AsyncWebhookAdapter object at 0x0000022B2CD76650>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\webhook\\async_.py\", line 204, in request\n    raise NotFound(response, data)\n          │        │         └ {'message': 'Unknown interaction', 'code': 10062}\n          │        └ <ClientResponse(https://discord.com/api/v10/interactions/997923941140144188/aW50ZXJhY3Rpb246OTk3OTIzOTQxMTQwMTQ0MTg4OllSYmMxS...\n          └ <class 'nextcord.errors.NotFound'>\n\nnextcord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n", "record": {"elapsed": {"repr": "0:02:53.786996", "seconds": 173.786996}, "exception": {"type": "NotFound", "value": "404 Not Found (error code: 10062): Unknown interaction", "traceback": true}, "extra": {}, "file": {"name": "master.py", "path": "C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py"}, "function": "get_users", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 141, "message": "An error has been caught in function 'get_users', process 'MainProcess' (18124), thread 'MainThread' (14408):", "module": "master", "name": "cogs.master", "process": {"id": 18124, "name": "MainProcess"}, "thread": {"id": 14408, "name": "MainThread"}, "time": {"repr": "2022-07-16 20:54:15.702183+03:00", "timestamp": 1657994055.702183}}}
{"text": "2022-07-16T21:07:23.824184+0300 | ERROR      | An error has been caught in function '_scheduled_task', process 'MainProcess' (5416), thread 'MainThread' (10236):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\bot.py\", line 77, in <module>\n    bot.run(config.get_token)\n    │   │   │      └ <property object at 0x000002C1E344EF70>\n    │   │   └ <_config.Config object at 0x000002C1E1687A30>\n    │   └ <function Client.run at 0x000002C1E219D5A0>\n    └ <nextcord.ext.commands.bot.Bot object at 0x000002C1E36C45E0>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\client.py\", line 796, in run\n    loop.run_forever()\n    │    └ <function ProactorEventLoop.run_forever at 0x000002C1E1490D30>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 600, in run_forever\n    self._run_once()\n    │    └ <function BaseEventLoop._run_once at 0x000002C1E13DE0E0>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1896, in _run_once\n    handle._run()\n    │      └ <function Handle._run at 0x000002C1E1371900>\n    └ <Handle Task.task_wakeup(<Future finished result=None>)>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n    │    │            │    │           │    └ <member '_args' of 'Handle' objects>\n    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>\n    │    │            │    └ <member '_callback' of 'Handle' objects>\n    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>\n    │    └ <member '_context' of 'Handle' objects>\n    └ <Handle Task.task_wakeup(<Future finished result=None>)>\n\n> File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\ui\\view.py\", line 390, in _scheduled_task\n    await item.callback(interaction)\n          │    │        └ <nextcord.interactions.Interaction object at 0x000002C1E36B20C0>\n          │    └ functools.partial(<function ListEmbedsView.show at 0x000002C1E36C8700>, <ListEmbedsView timeout=300 children=2>, <Button styl...\n          └ <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Список пользователей' emoji=None row=None>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\views.py\", line 451, in show\n    raise exc from exc\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\slavebot\\views.py\", line 441, in show\n    for f in self.embed.fields:\n             │    └ None\n             └ <ListEmbedsView timeout=300 children=2>\n\nAttributeError: 'NoneType' object has no attribute 'fields'\n", "record": {"elapsed": {"repr": "0:00:13.978999", "seconds": 13.978999}, "exception": {"type": "AttributeError", "value": "'NoneType' object has no attribute 'fields'", "traceback": true}, "extra": {}, "file": {"name": "view.py", "path": "C:\\Users\\phili\\PycharmProjects\\GuildsBot\\venv\\lib\\site-packages\\nextcord\\ui\\view.py"}, "function": "_scheduled_task", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 390, "message": "An error has been caught in function '_scheduled_task', process 'MainProcess' (5416), thread 'MainThread' (10236):", "module": "view", "name": "nextcord.ui.view", "process": {"id": 5416, "name": "MainProcess"}, "thread": {"id": 10236, "name": "MainThread"}, "time": {"repr": "2022-07-16 21:07:23.824184+03:00", "timestamp": 1657994843.824184}}}
